#+title: 网络文章@202402



------

[[https://www.betonit.ai/p/when-to-get-a-gmu-econ-phd][何时获得GMU经济学博士学位 - 作者：布莱恩·卡普兰 - 押注吧 --- When To Get a GMU Econ Ph.D. - by Bryan Caplan - Bet On It]]

Suppose, however, that the student can win admission to a top-25 program, is willing to suffer, but correctly believes that [[https://giving.gmu.edu/featured/masonomics-campaign-honors-a-legacy-of-ideas/][Masonomics]] is [[https://betonit.substack.com/p/the-ideologues-of-gmu][intellectually superior to mainstream economics]]. What then? My answer: _Go to the top-25 program anyway._ You can absorb everything that GMU economists know by reading our work and asking us questions via email and Zoom. We’re highly responsive to curious minds. Indeed, if you fit the preceding profile, you’d probably be welcome to spend your summers hanging out in my office building and joining us for lunch every day. A true scholar knows at least 10x as much about his subject as he learned in his official coursework, so don’t worry too much if your official coursework is a vast wasteland. I ought to know; after all, I went to Princeton.

然而，假设学生能够被录取进入排名前25的项目，愿意承受一些困难，但正确地认为梅森经济学在学术上优于主流经济学。那又如何呢？我的回答是：无论如何去那个排名前25的项目。你可以通过阅读我们的作品并通过电子邮件和Zoom向我们提问来吸收乔治梅森大学经济学家所知道的一切。我们对好奇的思维非常积极回应。实际上，如果你符合上述条件，你可能会被欢迎在我的办公楼里度过夏天，并每天与我们一起吃午餐。一个真正的学者对自己的专业至少了解比他在正式课程中学到的多10倍，所以如果你的正式课程是一片荒地，也不要太担心。我应该知道；毕竟，我曾就读于普林斯顿大学。

If you’re curious about getting a Ph.D. at GMU, I’m always happy to chat. Before we talk, however, please take everything above to heart. To wit:
如果你对在GMU获得博士学位感兴趣，我很乐意聊聊。然而，在我们交谈之前，请牢记上述所有内容。简言之：

Know your career goal.  了解你的职业目标。

Know why the intermediate option of the masters is almost always imprudent.
知道为什么硕士的中间选项几乎总是不明智的。

Know your preference for short-run suffering versus long-run career success.
了解你对短期苦难与长期职业成功的偏好。

Know you can learn all the Masonomics you desire while attending a competing school.
你可以在就读竞争学校的同时学习你想要的所有Masonomics知识。

And for God’s sake, if you want a Ph.D., apply to at least 15 schools!
求上帝的恩赐，如果你想要博士学位，请至少申请15所学校！
