#+title: 网络文章@202305

# 网络文章@202306

-----

[[https://www.dedao.cn/course/article?id=5Mr9mzb36pP4JL5R0AXkWqB2EYNegL&source=search][山姆·奥特曼的系统性野心（下） - 得到APP]](https://www.dedao.cn/course/article?id=5Mr9mzb36pP4JL5R0AXkWqB2EYNegL&source=search)

奥特曼的行事作风异于常人。比如非常讲求效率。他总是用最快的速度处理邮件和会议。如果他对你讲的东西感兴趣，他会全神贯注地盯着你听你讲话；如果他没兴趣他会很厌烦。他这种专注力甚至让人感觉他是不是有阿斯伯格综合征——也就是大脑有问题、但是对某些知识掌握得特别细的那种怪人——奥特曼说他不是。他还开玩笑说，为了让人相信他是一个正常人而非AI，他要练习多去几次厕所。

奥特曼有强烈的目标感，每年都要列一份目标清单，每隔几周看一次，想方设法把这几件事都做成。为了达成目标，他会一直工作、不惜累到病倒的程度。格雷厄姆的说法是「奥特曼非常善于变强大」。

奥特曼对新科技、新思想特别感兴趣，不但了熟于胸而且会用在生活上……比如说，他会告诉你微量的核辐射对身体有好处。

那为什么非得出来冒险呢？因为你要做一件了不起的事情。奥特曼认为，「做难的事情其实比做容易的事情更容易」——因为难的事情会吸引别人的兴趣，人们会愿意帮你一起做。同样是出来创业，你要说你们公司是做基因编辑的，大家会觉得这很有意思，会很愿意支持你；你要说我要再搞一个做笔记的APP，那没人在乎。

为了做难的事情，你需要有「绝对的竞争力」。这意味着你能做一些别人想模仿也模仿不好的事情，这也意味着你会非常反感平庸的东西。


第四个野心是建立一个宪章城市。也许在美国也许在国外某个地方，搞一个由商人和科技人员运行的、自我管理的全新型的城市。这个城市可能会有10万英亩土地，有5万到10万的居民。

奥特曼设想这个城市是21世纪的雅典，是一个精英社区，可以测试适应新技术的新管理方式，并且把主要管理职责交给AI。比如说，这里只允许自动驾驶汽车，不允许人类开车。再比如不允许任何人从房地产中赚钱。

……如果将来世界其他地方都陷入动乱，至少这个城市还是一个样板，能给人类保留一个希望。不过可能因为政策性的原因，这个项目目前尚未启动。

-----
[[https://www.dedao.cn/course/article?id=g258WANERjwQJDzlmgKbOMG1rZqkPl&source=search][累积出来的衰败 - 得到APP]](https://www.dedao.cn/course/article?id=g258WANERjwQJDzlmgKbOMG1rZqkPl&source=search)

秦制以来中国历代政府收税有个普遍规律，差不多是按照这样的节奏走——

1. 一开始，官方规定的“正税”，税率都不高，老百姓可以承受；
2. 随着政府规模变大，正税的税收已经不能维持运行，于是特别是地方政府，会发明各种新的名目收老百姓的钱，也就是苛捐杂税；
3. 苛捐杂税因为是灰色税收，容易滋生腐败，时间长了百姓怨声载道；
4. 这时候中央会搞一次税收改革，把所有杂税都合并到正税之中，来个正规化，简化手续，减少腐败——像唐朝的两税法、北宋王安石变法、明朝张居正的一条鞭法、清朝的摊丁入亩，都是如此；
5. 然而又过了一段时间，发现扩大后的正税又不够了，于是又开始征收新的杂税……

=====

公司也有东西在累积。

为什么公司做大了就容易僵化呢？根据鲁梅尔特在《关键难点》一书中的分析，我们大约可以说是因为一种「功臣文化」。

一家公司在历史上曾经有过非常辉煌的时期，造就了一批功臣，那么这些人从此之后就会把当初的做事方法给偶像化：我们这里就是这样做事的。

那么时间一长，再来新人，可就不能讲创新了，而是要讲服从、讲条例，要尊重老人的权威。老人纷纷要求提升自己的地位和势力范围，就好像一群老革命整天在那摆资历。公司坚定地生长着官僚主义。

简单说，是老人的资历和地位、用老方法做事的惯性在累积。

那你说怎么才能减轻累积呢？最简单的办法就是勤换人。「人」这种「子系统」的「多余功能」实在太多了。做官也好做事也好，你本来只是让这个人来工作，可是他会要求地位、他会发展自己的势力，他会想把亲朋好友也带来——你吸收一个人就等于吸收了一大堆人和事儿，岂能不衰败。最好在一个人生根发芽之前把他换掉。

这可能就是为什么大城市里的公司变僵化的速度比较慢。大城市里的公司有频繁的人员流动，跳槽、裁员、招聘都是家常便饭，人们本质上不是为一家公司、而是在一个职场圈里工作，就不太容易搞成树大根深。现代化的人才要么就有可替代性，要么就有易对接性，每个人都可以随时在另一家公司开展工作，那自然不容易腐化。

=====

我们这一讲全部要说的是，一个系统的衰败跟思想教育、组织纪律什么的关系不大，也不是文化的问题，而是无组织力量在暗中累积这个客观规律所导致的。就如同灌溉必然导致土地盐碱化一样。

要想基业长青，就必须用特别的制度抗衡累积过程。我们见过很多尝试，也取得了一定的效果，但是我们远远不能说已经解决了这个问题。

-----

[[https://www.dedao.cn/course/article?id=R2Mo65zY4QZ3Vn6OaVqEdNAa98jGBO&source=search][YC掌门人：给年轻人的建议 - 得到APP]](https://www.dedao.cn/course/article?id=R2Mo65zY4QZ3Vn6OaVqEdNAa98jGBO&source=search)

第五个建议和风险有关。大多数人都不太愿意承担风险。但山姆认为，一定要敢于承担更多的风险，尤其是你刚开始工作的时候。年轻和默默无闻其实是一个重要的竞争优势，因为这时候你几乎没有什么可以失去的。就算你失败了，也不要担心有什么问题，因为在生活中遇到的危机越多，下一次再遇到危机的时候，你害怕的就会越少。

山姆的第六个建议是，工资不能让你变得很富有。他说自己年轻的时候，觉得挣个不错的薪水就能变得富有。但是后来他意识到，想要致富，正确的方法应该是拥有价值能上涨的东西，比如股份。市场上还有一个很重要的套利机会，那就是“时间”。人们都希望在很短的时间赚到钱，所以一些长期的机会往往被忽视了。山姆说，正是这些机会帮他赚到了钱。所以和短期机会相比，长期的增长能让你赚到更多钱。你最好是在早期就去找这样的机会，如果失败了，没关系，你还可以继续尝试。

-----

[[https://lemire.me/blog/2023/06/14/citogenesis-in-science-and-the-importance-of-real-problems/][Citogenesis in science and the importance of real problems – Daniel Lemire's blog --- 科学中的细胞发生和实际问题的重要性——丹尼尔·勒米尔的博客]]

介绍一种 citogenesis 的现象，这种现象在科学界里面也比较常见：如果某个 claim 没有办法或者需要很高的成本才能进行验证的话，只要这种东西一旦流入权威的信息源，那么人们就会不断地重复和放大它。只有现实才能对这些情况进行矫正，可惜有很多领域是做不到这点的。

-----

[[https://world.hey.com/dhh/acting-your-wage-will-atrophy-your-abilities-1ca261c4][Acting your wage will atrophy your abilities --- “拿多少钱，干多少事”会萎缩你的能力]]

这篇文章说的非常好。如果你的技能不使用的话，就会萎缩掉。你肯定不想浪费自己的才华。所以不要使用类似 act your wage 这种行动（拿多少钱，干多少事），这样下来你浪费的只有自己的才华，并且最终一事无成。

And companies make employees feel like that all the time. This is part of what drives the whole “act your wage” rebellion. Why should you put in your best if work never seems to return the favor? It’s a perfectly human response of spite in the face of unfairness, but you can’t avenge your grievances by squandering your potential.

公司让员工一直有这种感觉。这是推动整个“行动你的工资”叛乱的部分原因。如果工作似乎永远不会得到回报，你为什么要尽力而为？面对不公平，这是完全人类的怨恨反应，但你不能通过浪费你的潜力来报仇。

Whatever the situation, whatever the company, you should show up with your very best. Not for them, but for you. Use the discontent to become better, then bolt to another camp when the opportunity presents itself.

无论情况如何，无论公司如何，您都应该全力以赴。不是为了他们，而是为了你。利用不满变得更好，然后在机会出现时跳到另一个阵营。

Besides, you’ll appreciate a good place so much more if you’ve made it through some bad places.

此外，如果你通过了一些糟糕的地方，你会更加欣赏一个好地方。

Don’t play yourself by living down to their expectations. Show yourself the path out by shining bright whatever the weather.

不要通过辜负他们的期望来玩弄自己。无论天气如何，都要闪耀着明亮的光芒，向自己展示出路。

-----

[[https://world.hey.com/dhh/we-need-not-all-be-connected-all-the-time-a4633c0e][We need not all be connected, all the time --- 我们不需要一直保持联系]]

看来 DHH 也被学校和家长之间这种即时通讯搞得怕了。


But what these wretched apps have wrought is a constant stream of needless communication and updates about life at school. Worse still, it's facilitated endless threads amongst parents on this thing or the other. And you're essentially obliged to partake in these non-stop chain mails, lest you miss a truly important or urgent message.

但是，这些可怜的应用程序造成的是源源不断的不必要的交流和关于学校生活的更新。更糟糕的是，它促进了父母之间关于这件事或另一件事的无休止的线索。你基本上有义务参与这些不间断的连锁邮件，以免错过真正重要或紧急的信息。


Not all connections benefit from having the friction removed by digital systems. Some barriers to interaction are good, actually. The fundamental premise that everything will be wonderful if we could just all be linked together everywhere, all the time is false.

并非所有连接都能从数字系统消除摩擦中受益。实际上，互动的一些障碍是好的。如果我们能随时随地联系在一起，一切都会变得美好的基本前提是错误的。

-----

[[https://world.hey.com/dhh/when-promotions-become-punishment-b1cc1430][When promotions become punishment --- 当升职成为惩罚]]

To be an effective manager, you have to be empathetic, but not too empathetic. Because if you can't separate yourself emotionally from the process, at least in part, you can't make the difficult-but-necessary decisions required to service the broader team. And it's really hard to know whether you have this in you until you're faced with the reality of a tough situation.

要成为一名有效的管理者，你必须善解人意，但不要太善解人意。因为如果你不能在情感上将自己与流程分开，至少部分地，你就无法做出为更广泛的团队服务所需的困难但必要的决定。在你面对艰难处境的现实之前，很难知道你是否拥有这种能力。

This is one of the key reasons to pursue minimalist management. By setting up processes that handle much of the mechanics of reporting, and clearly reveals someone's progress for all to see, as well as distributing the human elements, like mentorship, you can reap much of the benefit of letting senior people provide parts of the management work without the dreaded promotion into management per se.

这是追求极简主义管理的关键原因之一。通过建立处理大部分报告机制的流程，并清楚地揭示某人的进步供所有人看到，以及分配人为因素，如指导，你可以获得让高级人员提供部分管理工作的大部分好处，而不必被提升到管理层本身。


-----

[[https://www.inc.com/jeff-haden/37-years-ago-steve-jobs-said-best-managers-never-want-to-be-a-manager-science-says-he-was-right.html][37 Years Ago, Steve Jobs Said the Best Managers Never Actually Want to Be Managers. Science Says He Was Right | Inc.com --- 37年前，史蒂夫·乔布斯（Steve Jobs）说过，最好的经理人从来都不想成为经理。科学说他是对的 |Inc.com]]

[[https://www.youtube.com/watch?v=fj0hpsJvrko][Steve Jobs On Recruiting People - YouTube]]

You know who the best managers are? They're the great individual contributors who never, ever want to be a manager, but decide they want to be a manager, because no one else is going to be able to do as good a job as them.

你知道谁是最好的经理吗？他们是伟大的个人贡献者，他们从来不想成为经理，但决定要成为一名经理，因为没有人能像他们一样做好工作。

The next time you make a promotion decision, make sure you consider the great individual contributor who may not want to be a manager, but desperately wants to get things done.

下次你做出晋升决定时，一定要考虑那些伟大的个人贡献者，他们可能不想成为经理，但迫切地想把事情做好。

Because success always comes down to what your business accomplishes.

因为成功总是归结为您的业务所取得的成就。

Not what it manages. 不是它管理的东西。

-----

[Start them in the deep end](https://world.hey.com/dhh/start-them-in-the-deep-end-8c9c77fe)

因此，新员工在进入需要完成的实际工作的深渊之前，很少花超过一周的时间来熟悉环境。我一直很高兴看到，只要有机会，经常有人一开始就表现出自己是个优秀的游泳者。

不是每个人都会立即让你眼花缭乱，这也没关系。有些人确实需要更长的时间来适应，才能向你展示他们最好的一面。但这仍然是一个接触的功能。接触的挑战越多，大多数人就会越快发现自己熟悉对他们的要求。

你能对一个新员工做的最糟糕的事情就是让他们在组织的大厅里徘徊，没有充实的、有意义的、令人着迷的事情可做。每个值得聘用的人都想尽快地做出贡献。让他们来吧!
