#+title: 工作：巨变时代的现状、挑战与未来（The Job: Work and Its Future in a Time of Radical Change）

https://book.douban.com/subject/35686239/

** 序幕：坚不可摧

-----

“研究人员十分震惊。贫穷固然是件可怕的事情，但贫穷并不足以解释眼前的悲剧。村民是很穷，但还能吃饱饭——大多数人都有失业保险，还有一些人有养老金。他们拥有住房、家庭，当然，还拥有彼此。然而他们并没有联合起来做能做的事，比如带孩子上图书馆、组织学习小组，甚至，他们本可以站出来向政府提出更多的要求。事实却是，社区原子化，每个人都争先恐后地为自己抢夺一点好处。研究人员做了如下总结：靠救济金生活，既不是社会主义学者们所认为的那种振奋人心的经历，也不是穷人批判者们所说的“不事生产、享受闲暇”的借口。失业本身就是一个打击斗志、扼杀灵魂和制造危机的魔鬼。1971年发表的美国版研究报告中，研究者在前言部分做了如此概括：“闲暇被证明是一份悲剧性的礼物。”

马林塔尔调查第一次系统性地详尽分析了失业在经济、心理和精神方面的代价。作者列举了一些工作的“潜在功能”，如结构化的活动、共享的经验、地位和集体目标，没有这些，社会和许多个人就会分崩离析。他们甚至走得更远——将马林塔尔的懒散不安与纳粹征服奥地利联系起来。1938年，当希特勒带着对好工作的承诺吞并奥地利、工厂重新开张并被“雅利安化”之际，马林塔尔的居民才集体长舒了一口气。数年后，亚霍达写道：“能够对抗失业导致的萎靡的，只有工作。

-----

没有报酬，而非失业……女儿、母亲和妻子们都是如此。不过，性别差异在马林塔尔并没有起到那么大的作用。研究揭示的事实是，当工厂关闭后，有些男人也在继续支撑着自己与生活。他们也种蔬菜、养兔子。他们也花时间带孩子。尽管在技术层面上，他们没有被雇用，但他们顽强地做着那些有意义的事，这些事情将他们锚定在这个世界，使他们的生活井井有条。这些工作并不依赖雇主，而是他们自身的一部分。正如我在本书导言中提到的底特律年轻企业家所说，这些妇女和男子能够“在雇佣情境之外”维持工作，他们不仅更好地谋生，还能够过上更有意义的生活。马林塔尔的研究者们用“坚不可摧”来形容这些坚强的男人和女人。

** 少吃苦头

-----

需要多少年的疲惫和磨难，人们才能明白关于工作的简单真理：这样令人厌恶的东西，原来是避免经历人生艰辛，或者说，少吃苦头的不二之选。

-----

“在以色列，如果求职者被拒，他们往往归咎于制度。在美国，被拒的求职者更加倾向于自责。

沙龙把这种态度上的反差归因于他所描述的两种截然不同的招聘策略。在以色列，对求职者的筛选基于一种非个人化的客观程序，其重点是可展示的技能和证书，沙龙称之为“规格游戏”（specs game）。求职者接受关于其能力的严格盘问和测试，有时他们被淘汰的原因是那些和工作并不一定相关的技术细节和特质，比如年龄。这可能会让求职者愤怒，但并不会削弱他们的自尊。他们认为这不是他们的错，而是他们无法控制的不完美的、有时可以说是不公正的制度的错误。

“相比之下，在美国，求职者参与的是沙龙所说的“化学游戏”（chemistry game）。虽然可供展示的技能和证书是获得面试资格的关键，但它们通常并不足以让求职者最终被雇用。因此，求职者需要呈现沙龙所说的“人际化学反应”，也就是说，不仅要对工作本身，还要对其背后的机构展现出深刻的承诺。仅仅是想要、需要、能胜任一份工作是不够的。正如一家在线求职网站建议的那样：“从具有同等资格的群体中脱颖而出，求职成功靠的是‘合适’。”

-----

“这种原则不仅适用于戈雷利克这样的人所寻求的高薪白领工作，也适用于应届毕业生所寻求的基本入门级工作。我任职的学校建议学生提前准备好“电梯演讲”，以便面试的时候能够迅速地大肆吹捧他们的潜在雇主，同时表现得自己能够顺应公司主流的“组织文化”。炮制这样的“人际化学反应”，需要投入大量沙龙所说的“艰苦的情感劳动”，以维持一个“全新的人格面具”。这些劳动包括精心打造出一种修辞风格，来展现求职者对和雇主目标相匹配的自身职业愿景的激情。他们必须塑造这样的人设：既有团队精神，又有个人主动性，并且对公司提供的任何服务或产品永远充满热情。在玩这种“化学游戏”的过程中，许多申请者的自我价值感下降——他们认为，求职失败不能怪工作、雇主或体制，只能怪他们自己。我所访谈的许多人——机械师、服务员、药剂师——都把他们在工作上的困难，特别是找工作的困难，归咎于个人失败，而非他们无法控制的经济力量。沙龙告诉我，这是很典型的：在他的调查中，面对“我是否出了问题”这一题项，84%求职失败的美国人的回答是肯定的。”

-----

“这种想法似乎是有道理的。没有人喜欢磕磕绊绊的工作环境，古怪的人可能会把工作搞糟。但是，坚持要求员工“适应”某种“文化”，实际上是将他们化约为各种刻板类型，组织将面临被打造成回音室的风险：在这种环境中，组织中太多的人太容易相互认同，从而无法预见问题，当然也就看不到解决方案。而在一个具有多元视角的地方，这种弊端是可以被避免的。要求员工“适应”一个预先确定的模式还会产生另一个后果，即把能够胜任的人排除在外，仅仅因为他们在年龄、种族或个人气质方面不符合我们的预期类型。例如，高科技行业以将35岁以上的申请人称为“不合适”而臭名昭著；而建筑行业很难承认女性也会“适合”这份工作。对“适合”的过分关注可以解释，为什么如此多的雇主发现自己找不到“合格的”员工，因为他们往往将“合格的”定义为“和我一样”。比如前面提到的伊丽莎白就深受其害：雇主拒绝了她的求职申请，仅仅是为了录用某个自己信任的同类。”

-----

“当我们不能达到自己的期望时，就会倾向于认为自己做了“错事”，这种担忧播下了焦虑的种子。世界卫生组织的报告称，美国是这个星球上最焦虑的国家之一。这种压力在很大程度上源于工作中缺乏能动性的感觉。根据美国压力研究所（American Institute for Stress）的数据，由于过度的工作压力，美国每年在医疗保健、缺勤和减压治疗等方面，需要多支出3000亿美元以上。或许有点出人意料，各行各业都是如此。表面上看，努力进取的白领压力更大，但研究表明，蓝领工作者——如流水线厨师、工厂工人、实习护士——更加脆弱。奥弗·沙龙解释道，个中缘由在于蓝领工作的高强度和他们自身对工作的低掌控性，二者相结合，对健康产生了不利影响。高强度的工作不一定致病，但如果我们在高强度的工作中无法决定做什么、怎么做，这就很可能导致患病。对于越来越多的美国人来说——不管他们多么成功——这些压力已经让工作“面目全非：它曾是满足和自豪的源泉，如今成了一场充满焦虑的无形较量。“我们的身份不断受到考验，”沙龙告诉我，“不安全感，焦虑，如影随形。”

-----

“很难说清世道是何时变的，长时间工作成了高地位和有权力的象征。可以肯定的是，这一变化与二战后的经济繁荣和日益高涨的消费主义有关，它让工人愿意交出闲暇来换取额外的收入。但对领取高薪的高管阶层，这一点并不能完全解释他们的行为。怀特有如下表述：“总而言之，存在着这样的一类人，他们如此投入工作，以至于无法区分工作和生活——而他们很高兴自己将二者融为一体。”照这么说的话，今天的高薪雇员应该也是很开心的。最近的研究表明，在超时工作的可能性方面，收入最高的白领工人比收入最低的蓝领工人要高出一倍，尽管对于前者，这种加班基本上是没有报酬的。简而言之，在过去20年，美国最富有人群的闲暇时间出现了最大幅度的下降。至少可以说，他们在努力塑造忙忙碌碌的形象。我们的现任总统特朗普就是一个再典型不过的例子，他曾自豪地宣称自己是“首席工作狂”。”

-----

“为何如此多的富人热衷于吹嘘他们非凡的职业道德？其缘由尚不能确定。不过，有些社会科学家将其归因于“物以稀为贵”这一简单的经济学原则：当人们想要的某种东西短缺时——不管它是特定年份的钵酒、荷兰大师的绘画、黄金，还是人类的努力——我们都会更加珍视它，对它的欲望也就更加强烈。长时间工作就是一种令人看起来不同凡响的方式，它让某人显得对上司和同事都不可或缺。正如一位研究人员指出的，自愿性过度工作“由如下观念驱动：忙碌的人拥有一些优质的人力资本特征（如能力、抱负），因而是稀缺品，是就业市场所需要的”。还有一个或许更加险恶的因素影响到我们中的许多人，不仅是富人，即一种错误的信念：凡有利于工作的，就一定有利于做这项工作的人。”


-----

“你大概已经猜到了，“平地”也有阴暗面。由于缺乏经理的评判和支持，员工面临着巨大的压力，需要自行“适应当前的企业文化”。未能做到这一点的人或是被边缘化，或是被淘汰出局。几年前，该公司“选退”了20多名顶级工程师，其中包括游戏设计界传奇人物杰里·埃尔斯沃思（Jeri Ellsworth）。她后来与人合伙创建了一家新公司。在埃尔斯沃思看来，维尔福的公司架构是“伪扁平”的，其中隐藏着一层权威，其施加的压力类似于“要在中学同学小圈子里成为受欢迎的人”。埃尔斯沃思说，由于公司员工薪酬的很大一部分是基于同事们所感知的个人表现，因此大多数工程师都倾向于从事那些引人注目的、几乎肯定会成功的项目。她告诉我，总体而言，维尔福公司名义上鼓励大家去冒的那些风险，她的前同事们实际上唯恐避之不及。”


-----

“广为流传的“颠覆性创新”一词，源于哈佛商学院的经济学家克莱顿·克里斯滕森（Clayton Christensen）。他在1997年出版的畅销书《创新者困境》（The Innovators Dilemma）中提出这一概念，随即风靡商界，尤其是科技行业。然而，尽管雇主们常常鼓励员工要有“颠覆性”，但这个词的意思实际上并不确定，甚至有人怀疑，恐怕雇主们自己也是云里雾里。它似乎意味着希望员工能有主人翁精神，把自己当作企业主，勇于创新、勇于冒险来解决公司的问题。它假设每个人都能够且应该给组织的内部结构带来激动人心的变革。不幸的是，这一假设造成了诗人加里·斯奈德（Gary Snyder）曾经所说的“双重负担”。它暗示现有的程序至少是有缺陷的，因此，如斯奈德所言，我们不得不去“做一些理应更好、更不同的事情”。麻省理工学院的文化历史学家罗莎琳德·威廉姆斯（Rosalind Williams）曾经观察到，在这种思维模式下，如果有人抗拒变化——如果他们尊重前人的程序、创新和成就——那么，“他们就会饱受责难，没人认为守成是人类生活中不可替代且不可或缺的一部分”。也就是说，我们拒绝研究过去并从中学习，而是条件反射式地将它视为过时甚至无关紧要的东西。

这种傲慢让我们自食其果，其中有一些已经影响到了每一个人。我们可以把过去的工业时代想象成一个僵化的、令人窒息的等级制度的集合，盘踞其顶端的是一个抽着雪茄、拒绝变化的顽固精英；我们也可以把当下的“后工业时代”想象为去中心化、参与性的工作场所的集大成者，其控制和导向并非产生于条条框框，而是来自雇员一致认可的价值观和行动。然而，尽管这是一个非常理想的承诺，在实践中这个承诺却很难兑现。

-----

在早些年，管理理论学家詹姆斯·巴克（James Barker）仔细观察了一家小型制造商的变化过程。该制造商宣称公司已从等级官僚体制转变为一群自我管理的团队体制，即所谓“合弄制”（holocracy）。巴克注意到，当团队成员从管理监督中解脱出来时，他们往往比他们的前任老板对彼此施加更多的控制。在没有外部强加结构的情况下，这些员工形成了自己的等级制度和暴政。他们的工作时间变得更长。每个人都渴望被别人视为有价值的团队成员，为此他们牺牲了个人时间、家庭时间和身心健康。巴克写道：“同伴压力和理性规则的强有力结合……制造了一种新的铁笼，而囚禁于其中的人们，几乎意识不到这个铁笼的存在。”

-----

“神经学家发现，当我们察觉被人拿来与其他人做比较时，我们天生的“战斗或逃跑”（fight-or-flight）的反应就会起作用，释放出与压力有关的荷尔蒙，导致易怒、失眠和焦虑。“巨科技”公司的情形确实如此。由于存在这种因排序靠后而被炒的可能性，有些员工甚至会故意给同事使绊子。一位身心俱疲的工程师曾对沙龙说：“在这台跑步机上，你的额外工作将标准拉得很高，然后这被抬高的标准被重置为最低标准，再之后你不得不做更多的事情。”

** 爬出棺材

-----

“人们的普遍想法是，数字革命增加了对有技术的劳动力的需求，降低了对非技术劳动力的需求。”他说，“好吧，听上去没毛病，但我们谈论的是什么技术？似乎没有人知道——经济学家、其他社会科学家、任何人——都不知道。然而这显然是一个需要回答的重要问题。如果我们不知道怎样的技能可以真正带来回报，人们应该获取什么技能呢？因此，我们决定解构技能的概念，找出具体有哪些技能会带来最大回报。”

格拉斯基和他的同事仔细研究了社会科学家关于技能和好工作之间关系的假设。他们的发现令人吃惊。“大家都以为计算机技能是关键，”他说，“但从我们的发现来看，情况并非如此。最突出的是分析技能——批判性思维、逻辑思维和推理。”格拉斯基说，最容易获得这些分析技能的人，其成长环境使得他们在日常生活中便有机会磨炼这些技能。”


-----

“分析技能是通过权衡证据、识别模式，将问题概念化并在可获得信息——即便这些信息不够全面、完整——的基础上，解决问题的能力。它与定量技巧的不同之处在于，它不仅涉及了解规则，而且还涉及如何与何时打破规则。因此，尽管人们通常认为，所有学生都必须掌握“数学和计算机技能”，但光有这些技能还不够。要想获得成功，学生们需要的不仅仅是技术上的技能，他们还必须学会如何将这些技能应用于现实世界的问题，以及懂得将其应用到哪些问题上。分析性思维通常需要想象不同的情境和观点，思考有哪些有效的策略来处理它们，然后根据每个选项的预期效果做出判断。一般来说，相对富裕的人比那些处境不利的人更多接触到这种富有挑战性的思维方式，因而也就更有经验。这是因为，富人有更多的机会跳出日常生活的迫切需要去思考问题。”


-----

“纵观人类历史，用更少的资源做更多的事情可以提高效率，使我们的世界变得更美好。但现在可以说，在这个方面我们已经达到了一个极限。通过赋予机器更多类似人类的能力，我们似乎在越来越多的行业中、在价值链的大多数位置上减少了对人力的需求。数字技术使工人比以往任何时候都更有生产力，但随着时间的推移，生产力的提高并不总是导致工资或工作质量的提高。它也没有导致更多的人获得更具挑战或需要更高技能的工作。令人震惊的是：总体而言，数字技术导致了对高薪、高技能工作需求的下降。”


-----

“数字时代的资本主义似乎由于对就业机会进行两极分化威胁到了数字时代的民主——在高层增加了一些工作岗位，在底层增加了更多工作岗位，同时挤掉了许多稳定的中层工作岗位。来自美国劳工统计局的数据显示，增长最快的是低薪工作——护士助理、家庭保健助理、个人护理助理、餐馆（包括快餐馆）备餐师、女佣和门卫。虽然像软件设计师和计算机分析员这样的高薪工作也在增长，但它们的增长速度要慢得多。

麻省理工学院经济学家大卫·奥特尔（David Autor）说：“最强劲的就业增长并不是最高层次的增长，而是工资最低的那1/3岗位的增长。”尽管人们可能更愿意相信，我们的经济需要更多的工程师和科学家，但更大的需求是对服务人员的需求，这些人——至少在技术层面上——能力要低得多，对教育的要求也低得多。”


-----

“斯坦丁说：“我们已经将便携式工作的概念理想化了，我们总在宣扬，人们可以打包自己的技能，带着它们四处闯荡，并按自己设定的价格出售这些技能。当然，确实有人能够做到这一点。但是，认为我们可以通过这种模式建立社会而不需要任何对个人的保护，那只是一种幻想。所谓为自己工作的人实质上是在为暴君工作——你的价值仅仅在于你最终的工作表现。你总在被评估、被打分。一直要担心下一块面包在哪里，这意味着对自己的生活失去了控制。”


-----

“这样的案例表明，尽管雇主可能会抱怨农场工人——或兼职教师——“难找”，但这种困难并不一定来自真正的劳动力短缺。相反，基本的经济原则表明，劳动力过剩而不是短缺，才会使得雇主有底气提出低于标准的条件。一旦这些条件获得改善从而导致大量就业申请，“劳动力短缺”的说法就站不住脚了。”


-----

“也许，兼职的大学教师、农场工人和其他合同工确实可以灵活地在不同的工作岗位之间流动，但与此同时，他们当中也有许多人（如果不是大多数的话）宁愿放弃这种灵活性，来换取对自己工作生活的更多控制力。在IT公司、仓库、银行、保险公司和流水线上工作的数以百万计的美国人也是如此。他们的合同只承诺了灵活性，但没有带薪假期、病假、雇主赞助的医疗保险或其他通常为固定员工提供的福利。虽然目前还不清楚到底多少美国人是合同工，但毫无疑问，这个数字正在迅速增长。根据一些人的估计，到2020年代末期，美国私营部门近一半的劳动力都将体会到这种岌岌可危的状态。正如一位合同工在《华尔街日报》调查中的回答：“大型企业钟爱的灵活性转化为对以下问题的持续焦虑：是否明天你就会被宣布为‘冗员’？”


-----

“大约十年前，专业服务公司威利斯·托尔斯·沃森（Willis Towers Watson）在全球范围内对22个国家的2万名员工进行了调查。他们发现，大多数员工不再看重工作中的“灵活性”，而是渴望稳定。足有1/3的受访者表示，他们希望在整个职业生涯中只为1家公司工作，另有1/3的受访者表示，他们希望为总共不超过3家公司工作。除报酬外，稳定和工作保障优先于所有其他变量，包括“挑战”和“自主”等被吹得神乎其神的因素。一些专家将这归因于经济衰退的后遗症。他们预言，一旦经济复苏，工人的态度将会改变。但在2016年进行的一项针对3.1万名员工的后续调查中，这种感觉依然存在，工作稳定仍是最优先考虑的事项。

语言学家和社会批评家诺姆·乔姆斯基（Noam Chomsky）曾宣称，雇用临时工是企业商业模式的组成部分，目的是降低劳动力成本，增强“劳动力奴性”（labor servility）。对于越来越多的人来说，他的话是对的。如果没有安全保障，我们很少或根本没有手段来运用付出了高额代价才获得的灵活性——事实上，不少人在打不止一份工，仅仅是为了维持生计。我们日益不稳定的工作关系引发了压力，这种压力可能导致糟糕的人际关系、脆弱的健康状况和无能为力感，从而使人们难以掌控或做出改变。”

** 机器人该交税吗？

-----

“杰夫·贝佐斯常年向全公司的所有员工提供辞职补偿，而且他毫不掩饰自己对机器人的痴迷。在全球范围内，他的公司已经安装了10万多台机器人，据说它们与仓库中的人类“完美共生”。他还计划再增加成千上万的机器人员工。虽然还不清楚到底什么是“完美共生”，但根据亚马逊统计，机器人每年为每个仓库节省开支高达2200万美元。该公司的自主未来总体规划还包括使用无人机和自动驾驶的送货车辆。虽然贝佐斯坚称，这些都不会减少就业机会，但这话只能听听而已。亚马逊将继续在全球各地开设仓库，并为这些仓库增配预计总量10万的机器人。当这个目标实现之际，在亚马逊领取工资的每个员工——无论全职还是兼职——都能顶得上传统实体经营中的两个。”


-----

“在关于工作及其未来的讨论中，机器人的巨大身影若隐若现，这有可能使我们的对话深陷错误的假设。直到最近，许多经济学家都怀疑自动化能否永久性地大规模取代人类工作者。人们一直在放手让机器人去做那些它们更能胜任的工作，而根据“比较优势”的经济原则，可以预测人类将在那些对机器人最不利的领域保持优势。按照这种逻辑，技术不会取代我们，而是将赋予我们自由去做更少危险、更具挑战的事情，基本上，就是那些让人之所以为人的事情。

例如，在2016年，国家公路交通安全管理局正式承认“软件”为无人驾驶汽车的驾驶员，这是面向全国410万有偿司机——包括出租车、卡车、公共汽车和优步司机——的广而告之。但在竞争优势的名义下，这并不意味着砸掉他们的饭碗，而是让他们获得进入新角色的自由，他们可以去发明新型发动机，设计新型挡泥板，或接受那些只能依靠人类能力去应对的其他挑战。然而，近年来许多专家已指出，上述论证的问题在于，它建立在一个错误的前提上——即认为人类在承担大多数任务方面具有真正的优势。”

** 让他们去吃APP吧

-----

“因此，企业家精神并不一定会带来就业机会或经济增长。实际上，一个国家的企业家精神水平往往与其竞争力呈负相关。世界上最具创业精神的国家是乌干达，该国超过28％的工作者是企业家。世界第二大创业国是泰国，其次是巴西、喀麦隆、越南、安哥拉、牙买加和博茨瓦纳。我们当中很少有人会将这些国家误认为是创新或繁荣的动力源：2016年，乌干达的人均收入低于700美元。我们也不会把大多数美国小企业——美甲店、理发店、咖啡馆、清洁和园艺服务之类——误认成熊彼特所说的“进步引擎”。这些复制型的小企业可能很有创业精神，但它们创造的就业机会很少，提供能够维持生计的工资的岗位则更少。实际上，绝大多数新的小企业主并不打算建立一个雇用他人的公司，他们只想自我雇用。

初创企业也不比传统企业更具创新性或生产力。相反，企业的创新能力和生产能力往往随着经营年限的增加而提高。这意味着，那些已经建立很久的的、无趣的老牌公司才更有可能以富有成效的方式进行创新，而不是新的、活泼的初创企业，后者的寿命通常只有5年，甚至更短。”

-----

“我们对新鲜玩意儿孜孜不倦的追求——无论它们是新应用程序、新的饮食指南，还是新的视频游戏——有时会让我们忽视那些可以创造真正价值并带来稳定的高薪岗位的工作，我们会低估这些工作中的创新含量。但是，能够真正改善我们生活的那种创新并不容易，或者说，成本较高。私营部门曾经在基础研究中发挥了比今日大得多的作用，特别是在那些它们与公众部门共同投资的高风险、高回报的合资机构，例如施乐帕克研究中心、IBM研究院、杜邦实验室、贝尔实验室和微软研究院硅谷实验室。但近几十年来，这些机构和其他的类似机构纷纷被抛售、关闭或削减规模。很多时候，资金不再投向这些长期项目，而是被转而用于满足投资者的短期需求。在公共领域也发生了类似的事情。美国科学促进会报告说，在联邦预算总额中，研发比例从1965年的11.7%下降到了2016年的约3.4%。即便如此，特朗普政府还是认为这个比例太高了，2018年，涉及主要研究机构的政府预算被进一步削减了22％。”


** 激情悖论

-----

“在普拉特祖父的时代，很少有美国人能够奢侈地考虑其工作的意义，他们根本就不了解这意味着什么。只有极少数可以人尽其才、丰衣足食，今天也还是这样；在那个年代，大多数人并没有如此的期待，即便是像普拉特祖父那样的手艺人，这一点则和今天大不相同。过去，做手艺活儿通常需要驯服一个人的创造性倾向以适应市场的需求，而许多工匠觉得，这些限制在某种意义上反倒让他们更自由自在。普拉特的祖父是否曾在工作中寻求意义？他从未说过，但普拉特认为他能在自己干的活儿当中看见意义。“当我问我的祖父，‘你今天做了什么？’他可以给我一个明确的答案。”普拉特告诉我，“他很满足，并为此自豪。”但对于今天的许多人来说，这种满足感是飘忽不定的。“如果我们不生产具体有形的东西，如果我们不知道好工作与坏工作的标准，我们就很难从中得出意义。”


-----

“正如齐克森米哈利后来发现的那样，在被他人监视、评判并规定时间的情况下，很少有人能够达到心流状态。乔为自己的每一次精心焊接而感到自豪，但并非所有人都有机会长时间专注于特定的任务。例如，虽然高档餐厅的主厨可能会在设计并烹饪精致菜肴中获得心流，但快餐店员工就很难做到这一点。后者的工作无非是将冻土豆和热油倒进炸锅、服务顾客、收银、擦地板。即使好不容易进入忘我的心流，他们的反应或许会是惴惴不安。高端精品店的职员可能会因自己熟知面料和剪裁而信心满满，他们在与顾客分享这些专业知识的时候可能会体验心流，但折扣店的职员很难在接听电话、记录款项、折叠衣物和堆货等不断的任务切换中有此体验。独自工作的作家可能会在创作新小说时找到心流，但是一名在多项任务、截止日期和文山会海中挣扎的的广告文案会觉得，心流就像下班时地铁上的空位一般难以捕捉。

心流的概念或许可以追溯到哲学家弗里德里希·尼采，他强调保持乐观和建设性态度的重要性。尼采写道：“对必须要做的事情，不仅要忍受，还要爱它。”但在此，尼采并不是说我们可以学会爱工作。相反，他写道：人们美化“工作”，津津乐道“工作的福气”。在这些话语中，我看到了一个隐蔽的观念，如同对非私人化的有用行为的赞美，这种观念包含着对个人事项的恐惧。从根本上说，如今人们都感觉到工作的注视——而工作意味着从早到晚的劳碌——它相当于最好的警察，使每个人都不敢越雷池半步。它极大地阻碍了理性的发展，令人没有想法，不再渴望独立；它消耗了大量的心智能量，人们因而无法反思、冥想、做梦，也消除了忧虑爱恨；它设定了一个始终在眼前的小目标，保证你能轻松实现、定期满足。因此，一个人们持续地努力工作的社会将更加安全，而安全如今已被赋予至高无上的神性。

-----

如尼采所暗示的那样，齐克森米哈利也承认，大多数人对工作不满意。但现代社会的预期是，人们应该对工作充满热爱。由于这种预期，事情变得复杂，同时，人们被激发出更强烈的罪恶感。通过谷歌图书的词频统计器Ngram Viewer，我们可以发现“追随你的热爱”（follow your passion）这个词组在2008年出现的频率比1980年高出了将近450倍，那时候几乎没人这么说。回想一下《都市女孩》中的场景：女主角——一个大学毕业生——申请一份做纸杯蛋糕的工作却被拒，只因为她没有表现得很热爱在蛋糕上撒糖霜。这个桥段有趣而真实。“做你喜欢的事，这样你的工作目的就再也不是上班糊口”，我们无数次因听到这样的表述而热血沸腾。例如史蒂夫·乔布斯在斯坦福大学毕业典礼上的著名演讲：

你必须找到你喜欢的东西。工作、伴侣，都是如此。你的工作将占据生命的很大一部分，只有相信你的工作是伟大的，才能真正从中得到满足。做好工作的唯一途径就是热爱。如果你还没有找到它，继续寻找，不要安于现状。就像所有关乎内心的事情，当你找到它时，你立刻就会明白那种感觉。而且，就像任何伟大的关系一样，随着岁月的流逝，它会变得越来越好。所以，请继续寻找，在找到它之前，不要安于现状。

“不要安于现状”。好吧，我们知道这对乔布斯意味着什么。但这对其他人来说意味着什么呢？意味着大家都应该抛弃常规（以及他人的建议），梦想成为未来的英雄？是的，这是一个长盛不衰的美国式幻想，然而它只是幻想。仔细想想，大多数人都无法实现这个相当武断的目标。乔布斯“不要安于现状”的建议到底是什么意思？如果一个人的热爱——不管这种热爱得到多好的践行——不能给他带来薪水，这将是什么后果？毕竟，乔布斯最初热爱的是禅宗，但他并没有以此为职业。是否可以说，他在IT业中“安于现状”？乔布斯真的建议我们冒着破产的风险追求热爱吗？或者，他只是在建议我们努力让自己成为——或者假装成为——热爱工作的人，即便这份工作并非我们的真爱？”

“追随你的热爱”。一听到这话，人们就会通体舒畅、跃跃欲试。似乎可以一边将世俗弃如敝屣，一边获得世俗意义上的成功。表面看来，这种建议极具吸引力，但它依赖于一种滑稽的假设，即每个人都被上天赋予了一种激情，只要他下定决心、遵守纪律、努力工作，就能在职业生涯中获得好的回报。但这种幸运的巧合远没有我们以为的那么普遍。“工作中有多种激励，也有很多方法可以获得意义。”普拉特告诉我，“但要年轻人‘追随热爱’是一项危险的建议。大多数人从未找到过这种热爱，至少，他们没有找到能帮自己挣来工资的热爱。”

-----

“我问沙利文，撕扯鸡皮和错误报警如何给一份消防员的工作赋予意义。他冲了壶咖啡，然后开始梳理思绪。他说，像大多数消防员一样，想起自己扑救的第一场火灾，他仍会不由自主地心痛。当时他刚刚有了孩子，因为太多不眠之夜而筋疲力尽。尽管如此，当他在凌晨两点接到火警电话时，还是忍不住地兴奋。然而，当他走进烈焰熊熊的火场，他对这份工作的幻想烟消云散了。他眯起眼睛费劲地看，透过烟雾发现一个模糊的轮廓，看起来那像是一个瘫倒在椅子上的人，正在被火焰吞没。有那么一瞬间，沙利文大脑空白一片，等回过神来，他立刻冲进去救人。他离受害者越来越近，然后他意识到来不及了，那人已经死了。他说，这件事改变了他。他说：“我们和警察不同，他们负责隔绝：把青少年和酒精隔绝，把儿童和虐待者隔绝，把酒驾的人和驾照隔绝。而消防员大多数时候负责给予，我们需要保护公众的生命和家园，大家认为我们应该能帮到他们。可那一次，我们什么忙也帮不上。对那个被烧死的家伙，我们什么事也做不了。”

-----

“消防员不一定通过有些人所声称的方式——自主性，复杂性和直接奖励——从他们的工作中获得意义。相反，他们获得的意义似乎来自相互联接，这种类似“兄弟连”的情感为他们带来意义。对警察、士兵及许多其他行业的人也是如此。正如《纽约时报》文化评论家查尔斯·麦格拉思（Charles McGrath）所言，电视“行业剧”的吸引力在于：“很多人生命中的大部分时间都在职场度过，无论喜欢与否，我们的工作关系往往像家庭关系一样紧密。”对许多人而言，早上起床的动力不一定来自工作本身，而是来自这些关系。”


-----

“沙利文说：“为稳定收入而工作的消防员往往做得更好。对他们而言，工作就是工作。”但蒙召者的情况显然不同，尤其是被普拉特称为“火花”的那一类消防员。即使到了下班时间，他们也会坚守岗位。发生火警时，即使没有得到指令，他们也会擅自出现在火场。这样的无偿加班似乎是件好事，但有时并非如此。在我们的周围，总有一两个像这样过分积极的A型人。他们起到的作用恐怕是妨碍工作，将事情弄糟。沙利文说他认识不少这种人，若干年前，他团队里就有一个，此人给他留下了相当负面的记忆。“简直和纵火犯差不多，”他直截了当地告诉我。“他救火是为了逞英雄、寻求刺激。考虑到这一点，热爱工作并不总是好事。”

“词典将“激情/热爱”（passion）定义为一种强烈的、几乎失控的情感，而这并不是职场真正需要的东西。一个“充满热爱的”社会工作者可能会过度热心以至损害服务对象的利益；“充满热爱的”工程师为了抢先一步，可能会以不当方式破坏同事的业绩；“充满热爱的”警察可能会误将水枪当作真枪。许多工作需要专注，这点大家都同意。至于热爱，还是把它限制在关乎内心的事情上吧。”

-----

“直觉地看，所有这些都言之有理，然而无论是关于需求层级，还是雇主激发员工抱负的理论，马斯洛提供的实证证据都很少。事实是，不管是否可以自我实现，相比其最高时期，如今劳动者的满意度已大幅下降。调查显示，在20世纪50、60和70年代，大多数美国劳动者都在工厂工作，当时的雇主可给不了什么“有意义”的工作，但多达92％的调查对象表示对工作感到满意。令他们满意的原因不尽相同：当时占据劳动者比例很少的白领认为，挑战性是考量工作满意度最重要的因素，而作为当时大多数的蓝领工人优先考虑的是经济回报。相比于白领，蓝领工人更重视同事关系、工作时长、福利和职业安全感。基本上，蓝领工人看重的是稳定性、工作条件和人际关系，而挑战性对他们来说意义不大。”


-----

“人们很容易发出这样的疑问：仅仅因为这些二十几岁的人感觉上下班无意义，所有的人就该为此忧心忡忡吗？有一位应答者是刚刚毕业的大学生，他的答复触及了这个问题的深层。

可以肯定的是，我们这一代人被灌输了这样一种理念：只有花费在“做事情”上的时间才是有价值的，因为那是对未来的投资。追求个人兴趣算不上投资，因此我们努力地将工作当作兴趣所在。我们努力使工作符合自己的热爱，或者使自己的热爱符合工作要求。如果无法爱上工作，结果就是巨大的挫败感。假如对自我认同的追寻意味着个体被迫放弃自我的一部分以找到自我，这个模式无疑是有缺陷的。一个人是由他自身的欲望定义的，而热爱工作需要协调自己和雇主双方的欲望。如果说，工作给予人目的感，那么他的目的感就有赖于另一个人。他的自我便也掌控在另一人的手中。”

** 心灵的习性


-----

“许多人都记得被家人、亲戚和朋友，或是某次刻骨铭心的经历推向某条人生道路。瑞斯尼维斯基说，《心灵的习性》（Habits of the Heart）一书述及了此类现象。这本论文集于1985年首次出版。社会学家罗伯特·N.贝拉（Robert N. Bellah） ②在1996年的新版序言中写道：“（造成这些焦虑的）原因是，大多数美国人意识到，全球经济的增长不再意味着机会，而是‘缩小规模’‘重置工作岗位’，以及粉红色的解雇通知单。然而，尽管存在所有这些对于繁荣的可怕威胁，针对经济游戏规则的变化，几乎见不到什么公开的抗议。这点很奇怪。”


-----

“尽管如此，大部分动物园管理员都报告说，这份工作令他们着迷。一句话，他们感觉到了“蒙召”。许多人说，感觉自己注定要做这份工作，这是刻在自己的DNA当中的。用一位应答者的话来说，这些动物“为教育人类而放弃了自己的自由”，因而他深感有责任照顾它们。有些人觉得他们的动力如此之大，以至不给钱他们都肯干。事实上，确实有不少管理员在正式入职前，做了很多年不拿报酬的志愿者。

汤普森告诉我：“他们热爱自己的工作，这并不奇怪。但热爱工作并不总是件好事，至少不那么有利于被雇用的一方。我喜欢在杨百翰教书，但我对此并不多说，以免被利用。能做到全身心地投入工作是件好事，但有一个坏处，雇主们对此讳莫如深。实话实说，雇主们巴不得我们都以为自己是被‘神召’到工作岗位上的。”

一些雇主甚至专门聘请顾问去设计算法，以从应聘者当中挑选出“蒙召者”。他们认为这样的人将会愉快地处理任何任务而不会讲条件或提要求。瑞斯尼维斯基就曾被邀请设计这种算法，她礼貌而坚决地拒绝了。她说：“在这个时代，组织对员工提出了更多的要求。而组织所展示的往往类似于商场的橱窗，是美化过的，带有误导性。不是所有人都需要神召，也不是所有人都需要从工作中获得意义。”


-----

“杰森·爱德华·哈林顿（Jason Edward Harrington）在芝加哥奥黑尔机场的行李检查站工作了6年。他接受这份工作时刚刚大学毕业，还是个初出茅庐的自由撰稿人，所以当年他只是想临时干一段时间。后来，不知怎的，他就一直做了下来。他说，如果只是单纯的工作，他可能会坚持比6年更长的时间。他喜欢和来自世界各地的乘客打交道，有些乘客还觉得他挺有趣的。他无法忍受的是一个建立在怀疑基础上的体系。他的一举一动都被监控摄录，运输安全管理局声称这是为了保护他。有人对他说，假如乘客的iPad不见了，那么录像就可以证明这不是他的责任。哈林顿接受了这个说法，因为确实几乎每天都有人丢笔记本电脑和iPad。但问题是，主管们不遗余力查看录像带的目的，其实是去寻找他的哪怕是最轻微的违规行为，包括嚼口香糖、上洗手间。他说：“如果他们信任我们、尊重我们，这份工作还真的挺享受的。然而他们没有。所以，我们的通常做法是，争取跳槽机会（他认识的运输安全局员工每周都有人申请新岗位），如果暂时跳不了，就在上班时尽量远离摄像范围。”


-----

对员工的电子监控，包括使用摄像机的直接监控和通过软件进行的间接监控，在大多数行业中迅速发展，尤其是在“9·11”的悲剧性事件之后。没有人知道确切原因，但最可能的原因是技术的不断成熟和成本的不断下降。从DNA分析到眼球扫描，一系列越来越复杂的设备和技术使得雇主具备了监控能力，所以他们才有了监控行动。2/3的雇主会监控员工访问了哪些网站，近一半的雇主会监控员工的键盘输入。为了解员工在工作之余的活动，12%的雇主会关注他们的个人博客，10%的雇主会关注员工的社交网络账号。运输安全局用监控视频系统来监视负责行李安检机的工作人员，而几乎一半的雇主会使用类似设备对员工进行监控。甚至有一些公司认为，老板有权直接跟踪员工的私生活，例如通过公司发给员工的手机随时随地对他们定位。


-----

“迈克菲没有在论文中提到他是否和服务员当面交谈过。面谈很有必要。在他们的调查对象中，有一家名为“橄榄园”的休闲餐厅，它属于达登餐饮有限公司（Darden Restaurants, Inc.）。该公司是世界上最大的全方位服务餐厅，仅在美国就拥有2000多个营业点和约148000名员工。达登实施的不是以员工为中心的管理模式。举个例子，从2016年开始，达登将它一半美国雇员的传统工资条换成了电子工资卡。对公司而言，这又是一笔好生意：每张卡每天能为公司节省2.75美元的运营费用，所有的卡全年共节省500万美元。然而，对员工而言，工资卡导致了更大的开销：如果用它来缴水电费，每次交易要加上99美分手续费；如果在收银台刷卡失败，要被扣掉50美分；在未联网的ATM机取现，手续费是1.75美元；查卡余额要交75美分。如果丢了卡，就必须支付10美元来换新卡。这10美元可不是小数目：不算小费的话，橄榄园服务员的收入仅为每小时2.13美元。”


-----

“那么，当人们知道自己被监视时，他们在工作中是否会更有效率和生产力呢？这很难说。但如果工作场所的监控无处不在且日益复杂，这将充分暴露信任危机。有充分证据表明，如果员工感觉自己不被信任，他的工作效率就会降低。瑞斯尼维斯基说，如果一个人的工作被密切关注，其异化就会加速。他很难做到独立思考、主动行动，几乎无法从中获得意义。事实上，在工作中“作弊”的人经常都是为了报复信任的缺失。例如哈林顿跟我说的运输安全局的员工，他们挖空心思躲开转来转去的摄像头，不惜为此浪费大量时间。”


-----

“医院确实注意到了，但并不是那个意义上的“注意”。第二组清洁工受到了惩罚，被告知只管打扫便是。他们开始担心，再做分外之事，就有被炒鱿鱼的风险。瑞斯尼维斯基为此难过，但并不惊讶。她告诉我：“清洁工改善了病人的体验，但这种改善的价值是没法货币化的。现在，完成基本职责就是最高追求。我还从未见过一个将员工尊严视为终极价值的组织。”

作为需求层次范式的奠基人，心理学家马斯洛曾在日记中坦言，自己的理论是一种折中方案，试图在不冒犯主流意识形态的前提下，从组织精密的官僚层级中突围。他的目标不是直接帮助员工，而是帮助雇主创造一种将个人需求与组织需求自然融合的环境。对于马斯洛及其20世纪的许多同代人来说，这是一个双赢的策略——他们认为，如果员工感到幸福，则企业繁荣，个人也会从中受益。在某种程度上，那个年代的员工确实受益了。但如今，如何使组织目标与个人目标相一致？这个问题更趋复杂，也更加令人担忧。”


-----

“麦特利斯相信，她的发现所包含的意义远远超出艺术家的领域，而是几乎涵盖了任何职业。她说，全球经济蓬勃发展之际，在牢牢把握住工作身份的同时，我们也需要让自己独立于工作之外。她说，能做到这点殊为不易，因为如今所有人都面临着要“做到最好”的压力。

她告诉我：“雇主要求我们全力以赴，让我们和自己的岗位融为一体。他们希望员工通过专攻一个非常狭窄的领域来实现卓越。我们的价值取决于为组织所做的贡献。但这是一个非常危险的模式。今天你或许还是人上之人，如果明天被解雇或降职，你就将一无是处。如果——由于之前的工作——你是个特别专业化的人，你的技能无法应用到其他地方，你就失去了你的整个工作身份。这会是个可怕的精神打击。”

“在哪里找到意义，以及如何使工作有意义，这是一个高度个人化的问题。为谋生而工作是个非常实际的目标，还有另一层人性化的需要，即从工作中获得意义感。不同的人可以有不同目的。承认人各有志，我们或许可以得到解放和自由。虽然从工作中寻找意义是个健康甚至本质的追求，但并非所有人都能从具体岗位中获得这个意义，我们也不应该被期待或被强迫去这样做。”
